theme: jekyll-theme-slate
title: Welcome to Sachin github site
description: This github site is experimental site will grow gradually
lsi: false
safe: true
source: Sachin world
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
